'use client'

import localFont from "next/font/local";
import "./globals.css";
import { UfContextProvider } from "./Contexts/UfContext";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UfContextProvider>
          <Link href='/'>Home</Link>
          | <Link href='/cidadesContext'>Cidades da UF Selecionada</Link>
          <hr/>
          {children}
        </UfContextProvider>
      </body>
    </html>
  );
}
